research_topic: "The impact of AI on human society"
task_notes:
  - phases:
      - plan formulation
    note: You should come up with a plan for TWO experiments.

  - phases:
      - plan formulation
      - data preparation
      - running experiments
    note: Please use gpt-4o-mini for your experiments.

  - phases:
      - running experiments
    note: |
      Use the following code to inference gpt-4o-mini:
      from openai import OpenAI
      os.environ["OPENAI_API_KEY"] = "{api_key}"
      client = OpenAI()
      completion = client.chat.completions.create(
        model="gpt-4o-mini-2024-07-18", messages=messages)
      answer = completion.choices[0].message.content

  - phases:
      - running experiments
    note: You have access to only gpt-4o-mini using the OpenAI API, please use the following key {api_key} but do not use too many inferences. Do not use openai.ChatCompletion.create or any openai==0.28 commands. Instead use the provided inference code.

  - phases:
      - running experiments
    note: I would recommend using a small dataset (approximately only 100 data points) to run experiments in order to save time. Do not use much more than this unless you have to or are running the final tests.

  - phases:
      - data preparation
      - running experiments
    note: You are running on a MacBook laptop. You can use 'mps' with PyTorch

  - phases:
      - data preparation
      - running experiments
    note: Generate figures with very colorful and artistic design.
